version: "3.9"

services:
  nats:
    image: nats:2.10.22
    container_name: ttns
    restart: always
    command: [ "-c", "/nats.conf" ]
    ports:
      - '35700:4222' #websocket
    volumes:
      - ./nats.conf:/nats.conf
      - ttns_data:/data
volumes:
  ttns_data:
