WS_USER: "wsttuser1"
WS_PASSWORD: "$2a$11$TGhZqFKpXRiRbAplPeR1hu895loWHY/6mRJtlcsUgF8ny6YRyEv2u"

server_name: ttns1

jetstream: {

}

websocket {
    port: 6000
    no_tls: true
    authorization {
        username: $WS_USER
        password: $WS_PASSWORD
    }
}
