version: "3.9"

services:
  nats:
    image: nats:2.10.22
    container_name: nats
    restart: always
    command: ["-c", "/nats-server.conf"]
    ports:
      - '35600:4222'
    volumes:
      - nats_data:/data
      - ./nats-server.conf:/nats-server.conf

volumes:
  nats_data:
